### ISSUE TITLE
Transfer ownership to the Teclib Organization on GitHub

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/fastlane-plugin-xcov_report#11]
Hi, I will propose to move this repo to @teclib.

**Comment by ajsb85** [comment]
Hi, @orthagh 

Could you help us with this task?
This plugin can be integrate in any other project (iOS and Android) 👍 

Thank you.

**Comment by orthagh** [comment]
Hello @ajsb85 

You don't have admin right on this current repo ?

**Comment by ajsb85** [comment]
Done

https://github.com/TECLIB/fastlane-plugin-xcov_report

Thank you!
