### ISSUE TITLE
Project site

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/fastlane-plugin-xcov_report#5]
Hi, @Gianfranco97 

Could you create the project site of this repository?
Btw, we need to create a new Winstrap theme with the colors of the Teclib Edition logo guidelines.

Thanks

**Comment by ajsb85** [comment]
Hi, @Gianfranco97 

Why appear the Flyve MDM logo instead @teclib?

![image](https://user-images.githubusercontent.com/663460/32513562-d2ef4d66-c3fa-11e7-96e7-9e179d49ece6.png)

**Comment by ajsb85** [comment]
Here is the project site 👌 
http://flyve.org/fastlane-plugin-xcov_report/

**Comment by Gianfranco97** [comment]
Sorry, my mistake. I already solved it with this commit: 55e9e20c99dbafb5ba2f3e1eb52ae3639169300f
