### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/fastlane-plugin-xcov_report#6]
Hi, @Naylin15 

Please, create these files in this repository

- [x] README in markdown file format
- [x] LICENSE in markdown file format [The MIT License (MIT)]
- [x] GitHub templates for issues and PRs
- [x] Contribute Guidelines

Thank you.

**Comment by Naylin15** [comment]
Hi, @ajsb85 

I think this issue is finished

Greetings

**Comment by ajsb85** [comment]
Good job @Naylin15 

I will fill a new issue, to review the code documentation
